[package]
name = "sqlbarser"
version = "0.1.0"
authors = ["Super Bo <supernbo@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.md"
keywords = ["parser", "sql", "parsing", "bigquery", "snowflake"]
categories = ["parsing"]

[dependencies]
nom = "7.1.1"
